name: check

on:
  schedule:
    - cron: '0 12 * * *'


env:
  UPLOAD_BUILD: true

jobs:
  check:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7,3.9]
        platform:
          - "51"
        template:
          - "A"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          pio platform install https://github.com/OS-Q/P${{ matrix.platform }}/releases/latest/download/P${{ matrix.platform }}.zip

      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: OS-Q/T${{ matrix.platform }}${{ matrix.template }}
          token: ${{ secrets.OSQ_REPO_TOKEN }}
          path: T${{ matrix.platform }}${{ matrix.template }}

      - name: Build
        working-directory: T${{ matrix.platform }}${{ matrix.template }}
        if: success()
        id: build
        run: |
          pio run -d .
          echo "::set-output name=status::success"

      - name: mark report
        if: matrix.os != 'windows-latest'
        run: |
          echo "template ${{ matrix.platform }}-${{ matrix.template }} on ${{ matrix.os }} tested " >> report.txt

      - name: mark report
        if: matrix.os == 'windows-latest'
        run: |
          echo template ${{ matrix.platform }}-${{ matrix.template }} on ${{ matrix.os }} tested >> report.txt

      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: report
          path: report.txt

  report:
    needs:
      - check
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: notification
        uses: Qful/mqtt-action@master
        with:
          protocol: mqtt
          host: ${{secrets.MQTT_SERVER}}
          port: 1883
          username: ${{secrets.MQTT_USERNAME}}
          password: ${{secrets.MQTT_PASSWORD}}
          topic: ${{secrets.MQTT_TOPIC}}
          message: ${{ github.repository }}

