name: nightly

on:
  schedule:
    - cron: '0 14 * * *'

jobs:
  build:
    if: github.repository == 'OS-Q/S03'
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python: [3.7,3.8,3.9]
        tool:
          - "PIO"
          - "QIO"
        examples:
          - "examples/arduino"
          - "examples/native"
          - "examples/simba"

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: "recursive"
          fetch-depth: 1

      - name: Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}

      - name: Install PIO
        if: matrix.tool == 'PIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/platformio/platformio/archive/develop.zip
          pio platform install file://.

      - name: Install QIO
        if: matrix.tool == 'QIO'
        run: |
          python -m pip install --upgrade pip
          pip install -U https://github.com/OS-Q/S03/archive/master.zip
          qio platform install file://.
